### ISSUE TITLE
ACTION_IMAGE_CAPTURE causing 90 degree orientation to image

### ISSUE THREAD

**Issue by IomarSantos** [MLSDev/RxImagePicker#12]
This problem occurred in a galaxy s4

**Comment by Frederikos** [comment]
@IomarSantos 
Library gives you URI to file. Image orientation you can check by EXIF data.
There are a lot of solutions on client side:
http://stackoverflow.com/questions/3647993/android-bitmaps-loaded-from-gallery-are-rotated-in-imageview/3648017#3648017
