### ISSUE TITLE
requestImage doesn't call completion if user takes landscape photo in a portrait activity

### ISSUE THREAD

**Issue by canpoyrazoglu** [MLSDev/RxImagePicker#14]
My app is portrait only, and when I take a photo without rotating my phone (Galaxy S3), RxImagePicker works. However, if I take an image and while taking the picture I rotate my phone to take a landscape photo, the completion is never called in my app. I've also cross-posted the issue on SO (https://stackoverflow.com/questions/38000275/rximagepicker-not-calling-completion-if-orientation-changes-when-taking-image) and I was told that there's no way around this.

Is this true? What are all the other RxImagePicker users doing then? If not, how do I solve this issue?

**Comment by Frederikos** [comment]
@canpoyrazoglu 
You can check sample. It works fine with rotation.
Hidden activity is forced to portrait only - so onDestroy is not called.
But in your client activity you can add android:configChanges="orientation|screenSize" to manifest or save subscription.

**Comment by canpoyrazoglu** [comment]
I've already got `android:configChanges="orientation|screenSize|keyboardHidden"` in my manifest for the activity that I'm having the problem on.

**Comment by canpoyrazoglu** [comment]
I don't think this issue should be closed in that sense.

**Comment by Frederikos** [comment]
You can checkout sample app and try if it works on your device or not

**Comment by canpoyrazoglu** [comment]
The sample app works. I've even copy-pasted my problematic activity's manifest attributes to the sample app and it still works with them:

            android:windowSoftInputMode="stateHidden|adjustPan"
            android:screenOrientation="portrait"
            android:configChanges="orientation|screenSize|keyboardHidden"
            android:launchMode="singleTask"

But for some reason in my app, it doesn't work when I rotate. Not even the error handler is called. Just nothing.

**Comment by canpoyrazoglu** [comment]
For the record,

In normal behavior, `onActivityResult` is called on `HiddenActivity`. Then `onDestroy` is called.

When it's rotated, upon confirming the picture, `onDestroy` is called and the activity is recreated *before* `onActivityResult`. Then `onActivityResult` is called but `cameraPictureUrl` is `null`.

**Comment by Frederikos** [comment]
@canpoyrazoglu 
You using last version of library compile 'com.mlsdev.rximagepicker:library:1.1.7' ?
There was this issue is old version, and i put "portrait" in HiddenActivity to prevent recreation.

**Comment by canpoyrazoglu** [comment]
Yes, it was an old version, 1.1.2. I thought I was on the latest version for some reason.

Sorry.
