### ISSUE TITLE
Could you please provide library for select multiple image from Gallery 

### ISSUE THREAD

**Issue by nawaminp** [MLSDev/RxImagePicker#16]
Please

**Comment by Frederikos** [comment]
Not now. Maybe later.

**Comment by riadhnet** [comment]
I add my voice, this would be awesome

**Comment by ticofab** [comment]
+1

**Comment by Frederikos** [comment]
Added this feature in 1.3.0 version

**Comment by yookore** [comment]
Hi @Frederikos . It does not look like this feature is available on the build i generated from the sample app. I am running the build on Marshmallow. Digging into the code sample, I see that requestMultipleImages() is never used. How do we use this feature?

**Comment by Frederikos** [comment]
Hi @yookore
This is not main feature and sample app not using it.
I write sample request in readme : 
RxImagePicker.with(context).requestMultipleImages().subscribe(new Action1<List<Uri>>() {
            @Override
            public void call(List<Uri> uris) {
                //Get images by uris.
            }
        });
