### ISSUE TITLE
Opening Sources.GALLERY opens documents photo not real gallery

### ISSUE THREAD

**Issue by riadhnet** [MLSDev/RxImagePicker#17]
When selecting Sources.GALLERY , it opens documents , how to do to open the gallery apps installed in the phone ? 
something similar to this
 Intent intent = new Intent(Intent.ACTION_PICK, android.provider.MediaStore.Images.Media.INTERNAL_CONTENT_URI);
        context.startActivityForResult(intent, Constants.GALLERY_REQUEST);

**Comment by Frederikos** [comment]
It depends on Android version.
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                    pictureChooseIntent = new Intent(Intent.ACTION_OPEN_DOCUMENT);
                    pictureChooseIntent.addFlags(Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);
                } else {
                    pictureChooseIntent = new Intent(Intent.ACTION_GET_CONTENT);
                }

But if you need to use ACTION_PICK for some reason you can fork and change that.
