### ISSUE TITLE
Subscribe action is not fire if user check "Don't keep activity"

### ISSUE THREAD

**Issue by Tar-SSA** [MLSDev/RxImagePicker#22]
In standard implementation, both capture image with camera and pick image from gallery are working flawlessly

But one of my tester check "Don't keep activity" in android setting > Developer options to test what will happen, we found that

1.) the permission request flow seems to work fine
2.) but when take photo or choose image from gallery, the subscribe action is not fire.

How can we resolve this?

**Comment by Frederikos** [comment]
Fixed in 1.2.1 version

**Comment by Tar-SSA** [comment]
Thank you very much!
