### ISSUE TITLE
Camera permission not requesting

### ISSUE THREAD

**Issue by qvivr-jeffrey** [MLSDev/RxImagePicker#24]
This works great with picking a file from gallery, but when i use camera, it would crash due to no camera permission. I am using api Android N api 24.

**Comment by JigneshPatel23** [comment]
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.secreds/com.mlsdev.rximagepicker.HiddenActivity}: java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.oneplus.camera/.OPCameraServiceActivity clip={text/uri-list U:content://media/external/images/media/22405} (has extras) } from ProcessRecord{e60a080 21306:com.secreds/u0a189} (pid=21306, uid=10189) with revoked permission android.permission.CAMERA`

**Comment by B-greg** [comment]
same issue.

**Comment by PingForward** [comment]
It is asking about gallery permission when camera is selected! Fix please

**Comment by ReginFell** [comment]
Fixed in PR https://github.com/MLSDev/RxImagePicker/pull/39

Also, you can use fixed version via jitpack  
`compile 'com.github.ReginFell:RxImagePicker:b10033d507'`
