### ISSUE TITLE
RxImageConverters.uriToFile method not using subscriber.onCompleted(); 

### ISSUE THREAD

**Issue by rajchithathur** [MLSDev/RxImagePicker#27]
Hi team,
First thanks for this library,
I have doubt on RxImageConverters class

1.RxImageConverters.uriToFile onCreate not set subscriber.onCompleted(); 

Events are pushed to subscriber - **onNext**, **onError** and **onCompleted** methods on Subscriber are used to push the events onto it. As per [Rx Design Guidelines](http://go.microsoft.com/fwlink/?LinkID=205219), the events pushed from Observable should follow the below rules:
Zero, one or more than one calls to onNext
Zero or only one call to either of onCompleted or onError

from this [source](https://praveer09.github.io/technology/2016/02/21/rxjava-part-2-creating-an-observable/)

can you explain ?

Thanks for Advance
Rajesh Rajendiran

**Comment by Frederikos** [comment]
Thanks.
Yes you right. Fixed in 1.2.2 version.

**Comment by rajchithathur** [comment]
@Frederikos in version 1.2.2 onwards minsdkversion 16 why ?

**Comment by Frederikos** [comment]
https://developer.android.com/about/dashboards/index.html
Just deprecated old versions of Android
