### ISSUE TITLE
Subjects by default are not threadsafe RxImagePicker class

### ISSUE THREAD

**Issue by rajchithathur** [MLSDev/RxImagePicker#28]
Hi @Frederikos Subjects by default are not thread safe  [link!](http://tomstechnicalblog.blogspot.in/2016/03/rxjava-problem-with-subjects.html) .[RxImagePicker] (RxImagePicker/library/src/main/java/com/mlsdev/rximagepicker/RxImagePicker.java) class using PublishSubject Without Serialize ?

**Comment by Frederikos** [comment]
Yes. We have only one instance so we don't need to care about it.
