### ISSUE TITLE
Crashes when takes photo from camera

### ISSUE THREAD

**Issue by sohambannerjee8** [MLSDev/RxImagePicker#38]
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ints.elmerpro/com.mlsdev.rximagepicker.HiddenActivity}: java.lang.NullPointerException: file
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477)
> 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
> 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	at android.os.Looper.loop(Looper.java:148)
> 	at android.app.ActivityThread.main(ActivityThread.java:5438)
> 	at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:762)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
> 	Caused by: java.lang.NullPointerException: file
> 	at android.net.Uri.fromFile(Uri.java:452)
> 	at com.mlsdev.rximagepicker.HiddenActivity.handleIntent(HiddenActivity.java:82)
> 	at com.mlsdev.rximagepicker.HiddenActivity.onCreate(HiddenActivity.java:36)
> 	at android.app.Activity.performCreate(Activity.java:6251)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2370)
> 	... 9 more
> 	java.lang.NullPointerException: file
> 	at android.net.Uri.fromFile(Uri.java:452)
> 	at com.mlsdev.rximagepicker.HiddenActivity.handleIntent(HiddenActivity.java:82)
> 	at com.mlsdev.rximagepicker.HiddenActivity.onCreate(HiddenActivity.java:36)
> 	at android.app.Activity.performCreate(Activity.java:6251)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2370)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477)
> 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
> 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	at android.os.Looper.loop(Looper.java:148)
> 	at android.app.ActivityThread.main(ActivityThread.java:5438)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:762)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

**Comment by Frederikos** [comment]
Should be fixed in 2.2.0 version
