### ISSUE TITLE
Convert multiple Uri to File

### ISSUE THREAD

**Issue by afiqiqmal** [MLSDev/RxImagePicker#44]
how to use RxImageConverter in here from list of Uri to list of File

<pre>

RxImagePicker.with(getContext()).requestMultipleImages().flatMap(new Function<List<Uri>, ObservableSource<List<File>>>() {
                @Override
                public ObservableSource<List<File>> apply(@NonNull List<Uri> uri) throws Exception {
                    return // how to use RxImageConverter in here?
                }
            }).subscribe(new Consumer<List<Uri>>() {
                    @Override
                    public void accept(@NonNull List<Uri> uris) throws Exception {
                        //Get images by uris.
                    }
                });

</pre>

**Comment by Frederikos** [comment]
@afiqiqmal 
you should write your own Converter for this.
