### ISSUE TITLE
Delete pictures after uploading.

### ISSUE THREAD

**Issue by nishantt12** [MLSDev/RxImagePicker#46]
I am using RxImagePicker, I need to delete pictures after uploading. How can I find the exact path of the images? Currently, All the pictures are getting stored in PICTURE directory.

**Comment by nishantt12** [comment]
I guess you are using MediaStore.EXTRA_OUTPUT, that's why it's getting stored.

**Comment by Frederikos** [comment]
You have mediastore uri. if you want to get full path you can read this topic - https://stackoverflow.com/questions/3401579/get-filename-and-path-from-uri-from-mediastore

**Comment by nishantt12** [comment]
Thanks
