### ISSUE TITLE
Image picker fails to launch if Camera permission is not present in Manifest

### ISSUE THREAD

**Issue by timusus** [MLSDev/RxImagePicker#49]
The RxImagePicker library does not include `<uses-permission android:name="android.permission.CAMERA"/>` in the manifest. This is a good thing, as it means apps using this library don't automatically inherit that permission.

However, this also means that `HiddenActivity.checkPermission()` always fails, as we can't check for a permission that is not registered in the manifest.

I am able to reproduce this bug in the sample app on a Nexus 5X Running Android 7.0, a Nexus 6P running Android 7.0 and a Nexus 6P running Android 8.0.

The solution isn't simply to add the camera permission to the manifest. Some consumers of this library might only ever wish to retrieve images from the gallery. 

Will follow up with a pull request shortly.

**Comment by whalemare** [comment]
MLSDev, please apply pull-request and include this changes to library.

**Comment by Frederikos** [comment]
We actually don't need Camera permission to take picture using Intent.
I remove this permission in 2.0.2 version

**Comment by timusus** [comment]
Ah ok, so it looks like this bug was introduced in #39, where the camera permission request was introduced (unnecessarily) without also declaring the permission I'm the manifest.

**Comment by Frederikos** [comment]
If you add camera permission in main app then you need to request it before call library method, or it will crash.
But it's very rare case and you can easy handle it on client side.

**Comment by timusus** [comment]
I'm not someone experiencing the issue in #24, so I can't really say, but I would think this is not so easy to handle on the client side - it's easy to add the permission to the manifest, but there's no way for a client to add the permission check which was removed in d6830f41.

I don't disagree with what you're saying, but I feel like it's a bit of a regression from #24 & #39. Maybe we should provide a hook which allows a client to pass in which permissions are requested in `checkPermission()`.

**Comment by Frederikos** [comment]
1. This is rare case because apps that manipulate camera directly with Camera permission don't actually need Intent to launch camera and take a picture.
2. When you add Camera permission in manifest for some reason it's not hard to add

checkPermission(CAMERA) {
        pick image from camera
}

on client app. it's same as you work with standard android api that requires dynamic permissions. You don't need any hooks for that.

**Comment by timusus** [comment]
Ok, good call.

Resolved with d6830f4
