### ISSUE TITLE
Camera OK button not functioning

### ISSUE THREAD

**Issue by luthfi-leonhart** [MLSDev/RxImagePicker#52]
It happens in some devices I guess..
When I take a picture with camera and clicked OK, the camera activity doesn't close. But the picture has been saved, I checked it in the gallery app.
This is my code..it's a simple code actually..

`RxImagePicker.with(getContext()).requestImage(Sources.CAMERA).subscribe(new Consumer<Uri>() {
            @Override
            public void accept(@NonNull Uri uri) throws Exception {
                Glide.with(UserProfileFragment.this)
                        .load(uri)
                        .into(binding.photoLayout.profilePictureIv);
            }
});`

Btw, it happens on version 1.3.1 and 2.0.2. It's not happening in 1.1.7.
I can't use the old version because of FileUriExposedException in Android N.

Thank you.

**Comment by Frederikos** [comment]
Check 2.2.0 version
