### ISSUE TITLE
Convert Uri to Bitmap doesn't work for some images

### ISSUE THREAD

**Issue by zeeshanaslam78** [MLSDev/RxImagePicker#55]
I think there is nothing to do with RxImagePicker about this issue.

By capturing from camera with convert options Uri to Bitmap. It does show image in imageview And selecting image from gallery with same convert option It shows image in imageview successfully if image size is less than 2 MB other wise It doesn't show.
There is some issue with larger images.

I can see this warning 

> Bitmap too large to be uploaded into a texture (4160x3120, max=4096x4096)

It works properly with other two convert options [Load from Uri, Convert Uri to File]

**Comment by Frederikos** [comment]
You can't render big image bitmaps
https://stackoverflow.com/questions/10271020/bitmap-too-large-to-be-uploaded-into-a-texture
So if you don't want to use image loading libraries that do scaling work, you can manually downscale bitmap.
