### ISSUE TITLE
Not working when calling from a fragment

### ISSUE THREAD

**Issue by jahangirkabir** [MLSDev/RxImagePicker#6]
When i am calling RxImagePicker from a fragment application is closing after taking image or picking from gallery.
Is there any way to work it with Fragment ?

**Comment by Frederikos** [comment]
It works fine with Fragment, Dialog, etc...
Maybe you don't handle lifecycle correctly.
Application is closing? What crash you receive?

**Comment by jahangirkabir** [comment]
No crash, just application is closing after capturing image. Also on camera orientation its not working.Inside activity its working fine.
 

    On Friday, May 13, 2016 1:23 PM, Glebov Sergey <notifications@github.com> wrote:
 

 It works fine with Fragment, Dialog, etc...
Maybe you don't handle lifecycle correctly.
Application is closing? What crash you receive?—

**Comment by Frederikos** [comment]
Probably you don't handle orientation change.
Check updated sample app. It works with library from fragment.

**Comment by jahangirkabir** [comment]
I am calling imagepicker from Drawer Activity fragment 
So my drawer Activity is closing after calling image picker from a button click. then after choosing/capture image there is no drawer activity exist.Any solution ? 

    On Friday, May 13, 2016 1:56 PM, Glebov Sergey <notifications@github.com> wrote:
 

 Probably you don't handle orientation change.
Check updated sample app. It works with library from fragment.—

**Comment by Frederikos** [comment]
Your issue is not related to library.
Solution: maybe do not destroy receiver activity when you want to pick something.
