### ISSUE TITLE
Failure delivering result ResultInfo

### ISSUE THREAD

**Issue by nishantt12** [MLSDev/RxImagePicker#65]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=131173, result=-1, data=null} to activity.
com.mlsdev.rximagepicker.RxImagePicker.onImagePicked + 242 (RxImagePicker.java:242)
--
  | com.mlsdev.rximagepicker.RxImagePicker.onActivityResult + 90 (RxImagePicker.java:90)
  | androidx.fragment.app.FragmentActivity.onActivityResult + 160 (FragmentActivity.java:160)

I started getting this error after updating the RxImagePicker to the latest version. 

can you tell me how can I resolve this error?

**Comment by nishantt12** [comment]
can you review this PR? I am getting lots of crashes because of this.

https://github.com/MLSDev/RxImagePicker/pull/66

**Comment by Frederikos** [comment]
done
